name: Daily Biotech Report

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 6:00 UTC every day
  workflow_dispatch:      # Allows manual trigger from GitHub UI

permissions:
  contents: write         # Explicitly grant write permission

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for proper Git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser pandas beautifulsoup4 rich

      - name: Run report generator
        run: |
          python CB_science_tracker.py
          ls -la  # Debug: list files

      - name: Commit and push report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html || echo "No index.html to add"
          git status
          git commit -m "Update daily report: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin main || echo "Failed to push"
